#!/bin/bash

#Defaults
CRITICAL=100
WARNING=50

while getopts 'c:w:j:' flag; do
  case "${flag}" in
    c) CRITICAL="${OPTARG}" ;;
    w) WARNING="${OPTARG}" ;;
    j) JAIL="${OPTARG}" ;;
  esac
done

if [ -z $JAIL ] ; then
  echo "check_currently_banned [OPTIONS...]"
  echo "";
  echo "Check how many banned IP-numbers your selected JAIL has. returns warning or critical if exceeding set values."
  echo "";
  echo "Flags:";
  echo "  -c    value that critical is return, default: 100"
  echo "  -w    value that warning is return, default: 50"
  echo "  -j    name of fail2ban jail."
  echo ""
  echo "Exitcodes:"
  echo "  0     Jail is healty";
  echo "  1     Jail has more than -w IP-numbers blocked";
  echo "  2     Jail has more than -c IP-numbers blocked";
  echo ""
  echo "Example"
  echo "./check_currently_banned -w 100 -c 200 -j sshd"
  exit 3;
fi;

OUTPUT=`sudo fail2ban-client status $JAIL`
BANNED=`echo "$OUTPUT" | grep "Currently banned" | awk '{print $NF}' | tr -d '\n'`

if [ -z $BANNED ] ; then
  echo "Could not read output $OUTPUT";
  exit 3;
fi;

echo "Currently Banned: $BANNED";
if [ $BANNED -ge $CRITICAL ]; then
  exit 2;
elif [ $BANNED -ge $WARNING ]; then
  exit 1;
else
  exit 0;
fi;
