#!/usr/bin/python3
# for centos 7 run
# yum install python3 -y

import argparse
import sys
import json
import os

# Get arguments
ap = argparse.ArgumentParser()
ap.add_argument("-c", "--container", required=True, help="Name or id of container you want to check.",type=str)
ap.add_argument("-m", "--memory", required=False, help="Will output warning if memory limit is above this amount percentage. ex: 70 if you want to warn if memory consumptions exceeds 70%",type=float)
args = vars(ap.parse_args())

# Get data from command
output = os.popen('sudo podman stats --all --no-stream --format json')
containers = json.load(output)

for container in containers:
    if(container["name"] == args["container"] ):
        containerMemory = container["mem_percent"].strip('%')
        print("Memory usage is "+ containerMemory +"%")
        
        containerMemory = float(containerMemory)
        maxMemory = args["memory"]
        
        if maxMemory is not None and containerMemory > maxMemory :
            sys.exit(1)
        
        sys.exit(0)

print("Container "+ args["container"] +" is not running")
sys.exit(2)
