#!/bin/bash

# Defaults
CRITICAL=48
WARNING=24

while getopts 'r:c:w:' flag; do
  case "${flag}" in
    r) REPORT="${OPTARG}" ;;
    c) CRITICAL="${OPTARG}" ;;
    w) WARNING="${OPTARG}" ;;
  esac
done

if [ -z $REPORT ] ; then
  echo "check_last_modified [OPTIONS...]"
  echo "";
  echo "Reads text report and returns last modified file"
  echo "";
  echo "Flags:";
  echo "  -r    report file to read"
  echo "  -c    if latest file is older than this many hours report a critical error"
  echo "  -w    if latest file is older than this many hours report a warning"
  echo " "
  echo " "
  echo "Example"
  echo "./check_last_modified -r /home/backup/report"
  exit 3;
fi;

LINE=`head -1 $REPORT`
DATE=`echo $LINE | awk '{print $1}' | cut -d "." -f 1`
SIZE=`echo $LINE | awk '{print $2}'`
COPIES=`echo $LINE | awk '{print $3}'`
FILE=`echo $LINE | awk '{print $4}'`

NOW=`date +%s`
AGE=`expr $NOW - $DATE`
HOURS=`expr $AGE / 3600`

echo "$FILE is $HOURS Hours old with $COPIES copies.";

if [ $HOURS -ge $CRITICAL ]; then
  exit 2;
elif [ $HOURS -ge $WARNING ]; then
  exit 1;
else
  exit 0;
fi;
