#!/bin/bash

while getopts 'r:w:W:A:' flag; do
  case "${flag}" in
    r) REPORT="${OPTARG}" ;;
    w) WARNING="${OPTARG}" ;;
    W) WARNINGFILES="${OPTARG}" ;;
    A) MAXAGE="${OPTARG}" ;;
  esac
done

if [ -z $REPORT ] || [ -z $WARNING ] || [ -z $WARNINGFILES ] || [ -z $MAXAGE ]; then
  echo "check_size [OPTIONS...]"
  echo "";
  echo "Reads text report and returns total size";
  echo "";
  echo "Flags:";
  echo "  -r    report file to read"
  echo "  -w    if backup larger than this amount of bytes report a warning"
  echo "  -W    if backup consist of more than this amount of files report a warning"
  echo "  -A    if latest file is older than this many hours report a critical error"
  echo " "
  echo "Example"
  echo "./check_size -r /home/backup/report -c 200000000000 -w 100000000000"
  exit 3;
fi;

if [ ! -f "$REPORT" ] && [ ! -r "$REPORT" ] ; then
  echo "$REPORT does not exist or is not readable by this user $USER" ;
  exit 3;
fi;

FILES=`head -2 $REPORT | tail -n1`
FILES_HUMAN=`numfmt --to=si $FILES | tr -d '\n'`

SIZE=`head -3 $REPORT | tail -n1`
SIZE_HUMAN=`numfmt --to=si --suffix=B $SIZE | tr -d '\n'`

LINE=`head -1 $REPORT`
DATE=`echo $LINE | awk '{print $1}' | cut -d "." -f 1`
NOW=`date +%s`
AGE=`expr $NOW - $DATE`
HOURS=`expr $AGE / 3600`

echo "backup is $SIZE_HUMAN with $FILES_HUMAN files and is $HOURS hours old | \
HOURS=${SIZE} \
FILES=${FILES} \
AGE=$HOURS";

if [ $HOURS -ge $MAXAGE ]; then
  exit 2;
fi;

if [ $SIZE -ge $WARNING ] || [ $FILES -ge $WARNINGFILES ]; then
  exit 1;
fi;

if test `find $REPORT -mmin +2880`; then
  exit 1;
fi;

exit 0;