#!/bin/bash

while getopts 'r:c:w:C:W:' flag; do
  case "${flag}" in
    r) REPORT="${OPTARG}" ;;
    c) CRITICAL="${OPTARG}" ;;
    w) WARNING="${OPTARG}" ;;
    C) CRITICALFILES="${OPTARG}" ;;
    W) WARNINGFILES="${OPTARG}" ;;
  esac
done

if [ -z $REPORT ] || [ -z $CRITICAL ]  || [ -z $WARNING ] || [ -z $CRITICALFILES ]  || [ -z $WARNINGFILES ]; then
  echo "check_size [OPTIONS...]"
  echo "";
  echo "Reads text report and returns total size";
  echo "";
  echo "Flags:";
  echo "  -r    report file to read"
  echo "  -c    if backup larger than this amount of bytes report a critical error"
  echo "  -w    if backup larger than this amount of bytes report a warning"
  echo "  -C    if backup consist of more than this amount of files report a critical error"
  echo "  -W    if backup consist of more than this amount of files report a warning"
  echo " "
  echo "Example"
  echo "./check_size -r /home/backup/report -c 200000000000 -w 100000000000"
  exit 3;
fi;

if [ ! -f "$REPORT" ] && [ ! -r "$REPORT" ] ; then
  echo "$REPORT does not exist or is not readable by this user $USER" ;
  exit 3;
fi;

FILES=`head -2 $REPORT | tail -n1`
FILES_HUMAN=`numfmt --to=si $FILES | tr -d '\n'`

SIZE=`head -3 $REPORT | tail -n1`
SIZE_HUMAN=`numfmt --to=si --suffix=B $SIZE | tr -d '\n'`

echo "backup is $SIZE_HUMAN with $FILES_HUMAN files | HOURS=${SIZE};${WARNING};${CRITICAL} FILES=${FILES};${WARNINGFILES};${CRITICALFILES};";

if [ $SIZE -ge $CRITICAL ] || [ $FILES -ge $CRITICALFILES ] ; then
  exit 2;
elif [ $SIZE -ge $WARNING ] || [ $FILES -ge $WARNINGFILES ]; then
  exit 1;
else
  exit 0;
fi;
