#!/bin/bash

critical=200
warning=100
hours=24

while getopts 'w:c:d:h' flag; do
  case "${flag}" in
    c) critical="${OPTARG}" ;;
    w) warning="${OPTARG}" ;;
    d) hours="${OPTARG}" ;;
    h) help='true' ;;
  esac
done

if [ "$help" == "true" ]; then
	echo "check_failedlogins [OPTIONS...]"
	echo "";
	echo "nagios test, counts failed logins with sshd"
	echo "";
	echo "Flags:";
	echo "  -c    How many failed logins that has to be reached before returning critical"
	echo "  -w    How many failed logins that has to be reached before returning warning"
	echo "  -d    How many hours back in time we want to check."
	echo "  -h    Show thius help text.";
	echo "";
	echo "Example:";
	echo "check_failedlogins -c 200 -w 100 -d 24"
	exit 0;
fi;

if journalctl --version >/dev/null 2>&1; then
	failed=$(sudo journalctl -q --since "${hours} hours ago" | grep -i "sshd" |grep -i "Failed password" | wc -l)
else
	echo "journalctl is not installed."
	exit 3;
fi

if [ "$failed" -gt "$critical" ]; then
	echo "Critical - ${failed} failed logins in the last ${hours} hours | failed_sshd_logins=${failed};${warning};${critical}";
	exit 2
fi;

if [ "$failed" -gt "$warning" ]; then
	echo "Warning - ${failed} failed logins in the last ${hours} hours | failed_sshd_logins=${failed};${warning};${critical}";	
	exit 1
fi;


echo OK - "${failed} failed logins in the last ${hours} hours | failed_sshd_logins=${failed};${warning};${critical}";
exit 0
