#!/bin/bash

# Defaults
CRITICAL=2
WARNING=1

while getopts 'hmc:w:i:' flag; do
  case "${flag}" in
  c) CRITICAL="${OPTARG}" ;;
  w) WARNING="${OPTARG}" ;;
  m) MONITORTOOL=1 ;;
  h) HELP=1 ;;
  i) IGNORE="${OPTARG}" ;;
  esac
done

if [ $HELP ]; then
  echo "check_all_disks [OPTIONS...]"
  echo ""
  echo "Checks S.M.A.R.T values on all installed drives in the system"
  echo ""
  echo "Flags:"
  echo "  -h    This help page"
  echo "  -c    Returns a Critical error if more than this many drives are broken Default:2"
  echo "  -w    Returns a warning if more than this many drives are broken Default:1"
  echo "  -m    Use check_smart.pl from Napsty"
  echo "  -i    only used togheter with check_smart.pl Comma separated list of SMART attribute names or numbers which should be excluded (=ignored) with regard to checks"
  echo " "
  echo " "
  echo "Example"
  echo "./check_all_disks -c 2 -w 1 -m -i Reallocated_Sector_Ct=10"
  exit 3
fi

DRIVES=$(lsblk --nodeps -n -o name,tran)

TOTAL=0
OK=0
FAILED=0

echo "$DRIVES" | (
  while read -r DRIVE CONNECTION; do

    DIR=$(dirname "$0")
    if [ "$CONNECTION" == "sas" ] || [ "$CONNECTION" == "sata" ]; then
      if [ $MONITORTOOL ]; then
        if [ -z $IGNORE ]; then
          OUTPUT=$(sudo $DIR/check_smart.pl -q -i auto -d /dev/$DRIVE)
        else
          OUTPUT=$(sudo $DIR/check_smart.pl -q -i auto -d /dev/$DRIVE -w $IGNORE)
        fi
      else
        sudo /usr/lib64/nagios/plugins/check_ide_smart -d /dev/$DRIVE
      fi
      RESULT=$?
      TOTAL=$((TOTAL + 1))
      if [ "$RESULT" -eq "0" ]; then
        OK=$((OK + 1))
      else
        echo "/dev/$DRIVE FAILED ($DIR/check_smart.pl -q -i auto -d /dev/$DRIVE)"
        FAILED=$((FAILED + 1))
      fi
    fi

  done

  echo "${OK}/${TOTAL} DISKS ARE OK | TOTAL=${TOTAL} | OK=${OK} | FAILED=${FAILED}"

  if [ $FAILED -ge $CRITICAL ]; then
    exit 2
  elif [ $FAILED -ge $WARNING ]; then
    exit 1
  else
    exit 0
  fi
)
