#!/usr/bin/python3


import argparse
import sys
import json
import os
import subprocess

def check_remote(ssh, host, username, command, directory, certificates, ignore):
    remmote_command = f"{command} -H {directory}"

    if len(certificates):
        remmote_command += f" -c {' '.join(certificates)}"

    if len(ignore):
        remmote_command += f" -i {' '.join(ignore)}"

    check_command = [ssh, "-H", host , "-l", username, "-C", remmote_command]
    process = subprocess.run(check_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)

    print(process.stdout)
    sys.exit(process.returncode)

def main():
    parser = argparse.ArgumentParser(description="Check Podman with multiple containers.")
    parser.add_argument("-s", "--ssh", type=str, help="Specify container(s) to check", default="/usr/lib/nagios/plugins/check_by_ssh")
    parser.add_argument("-H", "--host", type=str, help="Specify container(s) to check", required=True)
    parser.add_argument("-U", "--username", type=str, help="Specify container(s) to check", default="icinga")
    parser.add_argument("-c", "--certificates", nargs='+', help="Specify the domainnames that are being monitored.", default=[])

    parser.add_argument("-p", "--command", type=str, help="Specify container(s) to check", default="/home/icinga/bin/web/check_certificates_missing")
    parser.add_argument("-d", "--directory", type=str, help="Specify the directory to check for certificates", default="/etc/letsencrypt/live/")
    parser.add_argument("-i", "--ignore", nargs='+', help="Certificates that should be ignored.", default=[])

    args = parser.parse_args()

    check_remote(args.ssh, args.host, args.username, args.command, args.directory, args.certificates, args.ignore)

if __name__ == "__main__":
    main()